version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest
      - run:
          name: Run tests
          command: |
            pytest
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/test_driven_development:v1 .
      - run:
          name: Push to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/test_driven_development:v1cimg/python:3.8

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
